# Generated by Django 5.2.6 on 2025-09-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract')], default='full_time', max_length=20),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='work_scope',
            field=models.CharField(choices=[('inside_country', 'Inside Country'), ('outside_country', 'Outside Country'), ('remote', 'Remote')], default='inside_country', max_length=20),
        ),
    ]
